baseURL = "https://caldiss-aau.github.io/sdsphd19/"
languageCode = "en-us"
title = "AAU Social Data Science PhD 2019"
themesDir = "themes"
theme = "whisper"
enableEmoji = true

pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
pygmentsUseClasses = true

# Controls how many words are printed in the content summary on the docs homepage.
# See https://gohugo.io/content-management/summaries/
summaryLength = 30

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

[[menu.main]]
    name = "Course material"
    url = "/material/"
    weight = 2

[[menu.main]]
    name = "Info"
    url = "/info/"
    weight = 2


[params]
  mainSections = ["material", "info"]
  google_analytics_id=""
  homepage_button_link = '/material'
  homepage_button_text = 'Go to the course material'
  homepage_intro = 'Whisper is a documentation theme built with Hugo. The design and functionality is intentionally minimal.'
  #homepage_image = '/images/aal_back.jpg'
  homepage_image = 'img/front_nlp.gif'

  ## You can enable to add anchor links to header elements
  # enable_anchor_link = true

  [params.homepage_meta_tags]
    meta_description = "An Applied Introduction to Machine Learning for Social Science And Humanities Scholars"
    meta_og_title = "The Social Data Science PhD Course 2019"
    meta_og_type = "website"
    meta_og_url = "https://caldiss-aau.github.io/sdsphd19/"
    meta_og_image = "https://rawcdn.githack.com/RJuro/sdsphd19_source/b41578d0a60e132054adebb91dfe9e658e57745c/static/meta_prev.png"
    meta_og_description = "An Applied Introduction to Machine Learning for Social Science And Humanities Scholars"
    meta_twitter_card = ""
    meta_twitter_site = ""
    meta_twitter_creator = "caldiss.aau.dk"

  [params.logo]
      mobile = "/images/logo_aau.png"
      standard  = "/images/logo_aau.png"
